
spring.datasource.url=jdbc:mysql://localhost:3306/minha_estante?useTimezone=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Suasenhaaqui


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true